# Generated by Django 4.1.5 on 2023-01-13 17:02

from django.db import migrations, models
import tauth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('login_url', models.URLField()),
                ('redirect_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SSOUser',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_services', models.ManyToManyField(to='tauth.adminservice')),
            ],
            bases=(tauth.models.TimestampMixin, models.Model),
        ),
    ]
